mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('create', views.QuestionCreate.as_view(), name='create')
    path('create', views.createQuestion, name='question_create')
]

polls/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    limit_date = models.DateTimeField()
    visible = models.BooleanField(default=True)
    authors_name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name = 'Nome do autor')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from polls.models import Question


class QuestionForm(forms.ModelForm):

  class Meta:
    model = Question
    fields = ('question_text', 'limit_date', 'pub_date')

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from datetime import datetime
from .forms import QuestionForm

from django.views import generic
from django.views.generic import CreateView
from django.utils import timezone


from .models import Choice, Question



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            visible=True
        ).order_by('pub_date')

def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')


def createQuestion(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)

        if form.is_valid():
            polls = form.save(commit=False)
            polls.done = 'doing'
            polls.save()
            return HttpResponseRedirect("/")
            #return redirect('/')
            #return render(request, 'polls/index')

    else:
        form = QuestionForm()
        return render(request, 'polls/question_create.html', {'form': form})


# class QuestionCreate(CreateView):
#     model = Question
#     fields = ('question_text', 'limit_date',)
#     success_url = reverse_lazy('polls/')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    extra_context = {'now': timezone.now}

    def get_queryset(self):
        if timezone.now() > timezone.make_aware(datetime(2022, 12, 18)):
            return Question.objects.none()
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Polls</title>{% endblock %}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <p class="navbar-brand">Fifa World Cup 2022 Polls</p>
      </div>
      <ul class="nav navbar-nav navbar-right">
       
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li ><a href="{% url 'polls:index' %}">Polls</a></li>
        {% endif %}
        
      </ul>
    </div>
  </nav>


</body>
</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
    <input type="submit" value="Vote"
 {%  if now > question.limit_date %}
       disabled
    {% endif %}
    >
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Polls</title>{% endblock %}

 
 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>


<body>

    <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <p class="navbar-brand">Fifa World Cup 2022 Polls</p>
          </div>
          <ul class="nav navbar-nav navbar-right">
           
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li ><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            <li><a href="{% url 'polls:question_create' %}">Create Poll</a></li>
            {% endif %}
            
          </ul>
        </div>
      </nav>
    

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    <p>{{ question.limit_date }}</p>

    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/question_create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Question</title>
</head>
<body>

  <h1>Insert your question:</h1>

  <form method="POST" action="/polls/">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send">
    <button type="reset"> <a href="{% url 'polls:index' %}">Cancel</a></button>
  </form>
  


</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Return</a>